theme: jekyll-theme-hacker
title: Welcome to Saurav's beginner guitar lesson homepage!
Description: This site was prepared to list the items to teach Arushi Shory, a complete beginner how to play the guitar.
